from typing import List, Dict, Any
import json

class ReportGenerator:
    @staticmethod
    def generate_markdown_report(filename: str, analyses: List[Dict[str, Any]]) -> str:
        """
        Generates a comprehensive Markdown report from a list of analysis results.
        """
        report = []
        report.append(f"# Analysis Report: {filename}")
        report.append(f"**Generated by ML Agent**\n")
        
        report.append("## Executive Summary")
        # Synthesize a high-level summary (could use LLM here, but simple concatenation for now)
        summary_points = []
        for res in analyses:
            summary_points.append(f"- **{res.get('summary', 'Analysis')}**: {len(res.get('insights', []))} key findings.")
        report.append("\n".join(summary_points))
        report.append("\n---\n")
        
        for i, res in enumerate(analyses):
            title = res.get('summary', f"Analysis {i+1}")
            report.append(f"## {i+1}. {title}")
            
            # Insights
            report.append("### Key Insights")
            for insight in res.get('insights', []):
                report.append(f"- {insight}")
            
            # Charts (ASCII/Description placeholder)
            charts = res.get('charts', [])
            if charts:
                report.append("\n### Visualizations")
                for chart in charts:
                    c_title = chart.get('title', 'Chart')
                    c_type = chart.get('type', 'unknown')
                    report.append(f"**{c_title}** ({c_type} chart)")
                    # In a real report, we'd embed the image or JSON data. 
                    # For Markdown, we can just list the data summary or a placeholder.
                    report.append(f"> *[Chart Data Available in Dashboard]*")
                    report.append("")
            
            # Narration
            narration = res.get('gemma_narration')
            if narration:
                report.append("\n### AI Narration")
                report.append(f"_{narration}_")
            
            report.append("\n---\n")
            
        report.append("\n*End of Report*")
        return "\n".join(report)
