"""Schemas package for ML Service analytics."""

from .analytics_models import (
    AnomalyRequest,
    ClusterRequest,
    FinancialDashboardRequest,
    PredictRequest,
    PredictionVisualizationRequest,
    PremiumAnalysisRequest,
    QuickAnalysisRequest,
    RAGEvaluationRequest,
    SmartAnalyzeNextRequest,
    SmartAnalyzeRequest,
    StandardEngineRequest,
    StatisticalAnalysisRequest,
    TitanPremiumConfigRequest,
    TitanPremiumNextRequest,
    TitanPremiumRequest,
    TrendRequest,
    UniversalGraphRequest,
)

__all__ = [
    "StatisticalAnalysisRequest",
    "UniversalGraphRequest",
    "RAGEvaluationRequest",
    "PredictRequest",
    "AnomalyRequest",
    "ClusterRequest",
    "TrendRequest",
    "QuickAnalysisRequest",
    "StandardEngineRequest",
    "TitanPremiumRequest",
    "TitanPremiumNextRequest",
    "TitanPremiumConfigRequest",
    "PremiumAnalysisRequest",
    "FinancialDashboardRequest",
    "PredictionVisualizationRequest",
    "SmartAnalyzeRequest",
    "SmartAnalyzeNextRequest",
]
